version: '3.8'

services:
  vending-api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: python app/application.py
    image: fondleaderbot-api
    container_name: fondleaderbot-api
    restart: always
    ports:
      - "80:5000"
    env_file:
      - ".env"
    volumes:
      - ./logs:/app/logs
    network_mode: "host"
