[tool.poetry]
name = "FondLeaderBotAPI"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.8"
tortoise-orm = "^0.16.16"
fastapi = "^0.61.1"
asyncio = "^3.4.3"
uvicorn = "^0.12.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
